# This is a config for E2B sandbox template.
# You can use template ID (7hrj481kwrksdv3irpkt) or template name (arjun) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("arjun") # Sync sandbox
# sandbox = await AsyncSandbox.create("arjun") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('arjun')

team_id = "7c3b783c-d9f3-4531-8278-f1df5cc9a8a3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "arjun"
template_id = "7hrj481kwrksdv3irpkt"
